import { ColumnType, Generated, Insertable, Selectable, Updateable } from "kysely";

import { ConvertStatus, MediaDirection } from "../types/convert";

export interface ConvertTable {
  // Columns that are generated by the database should be marked
  // using the `Generated` type. This way they are automatically
  // made optional in inserts and updates.
  id: Generated<number>;

  direction: MediaDirection;
  status: ConvertStatus;
  file_hash: string;
  message: string | null;
  download_url: string | null;
  created_at: ColumnType<Date, string | undefined, never>;
}

export type Convert = Selectable<ConvertTable>;
export type NewConvert = Insertable<ConvertTable>;
export type ConvertUpdate = Updateable<ConvertTable>;

export type GetConvertOpts = Pick<Convert, "direction" | "file_hash">;
